### ISSUE TITLE
did not found web-animations.min.js?

### ISSUE THREAD

**Issue by bhumin3i** [web-animations/web-animations-js#109]
did not found two js file 
1) web-animations.min.js.map
2) web-animations.min.js

found reference using 
https://www.joshmorony.com/using-the-web-animations-api-in-ionic-2/

**Comment by zenismaharjan** [comment]
Same here, didn't found js file:

web-animations.min.js.map
web-animations.min.js

found reference using:
https://www.joshmorony.com/using-the-web-animations-api-in-ionic-2/

**Comment by christinakayastha** [comment]
This is probably because you are looking at the dev branch, you can find these files here:

https://github.com/web-animations/web-animations-js/tree/master

**Comment by bhumin3i** [comment]
thanks a lot. :+1:
