### ISSUE TITLE
web-animations-js should have a bower.json

### ISSUE THREAD

**Issue by nik3daz** [web-animations/web-animations-js#11]
This repo doesn't have a bower.json. This means that the 780K test/ directory is installed when using bower. This is particularly troubling because this is a dependency of Polymer so this has been bloating packaged apps built with Polymer through bower.

A bower.json file should be added which ignores (at least) the test directory.

**Comment by rjwright** [comment]
bower.json added in https://github.com/web-animations/web-animations-next/pull/296
