### ISSUE TITLE
"undefined is not a function" in Chrome version 22.0.XX

### ISSUE THREAD

**Issue by thomasgazzoni** [web-animations/web-animations-js#112]
Hi guys, I am using this polyfill (web-animations.min.js to be specific) in a website which is visited by some users that are still using **Chrome** version **22.0.XX** and I got this error stack-trace:

```sh
Uncaught TypeError: undefined is not a function
window.requestAnimationFrame
b.restart
f._play
window.Element.animate 
```

Debugging a bit this error come from those lines:

```javascript
...
var i = window.requestAnimationFrame, j = [], k = 0;
window.requestAnimationFrame = function(a) { 
   var b = k++; 
   return 0 == j.length && i(d), j.push([b, a]), b
},
...
```
seems the **i(d)** function is undefined? or better the **j** is a empty array? I can't figure out this logic yet, so I just reporting it first and see if someone can help me out a bit to get a workaround.

Thanks.

**Comment by ewilligers** [comment]
https://www.chromestatus.com/feature/5233400470306816
shows that requestAnimationFrame was introduced in Chrome 24.

A workaround would be 
window.requestAnimationFrame || window.webkitRequestAnimationFrame


docs/support.md doesn't specify which is the earliest supported Chrome version.

"The polyfill is supported on modern versions of all major browsers, including:
* Chrome
* Firefox 27+
* IE10+ (including Edge)
* Safari (iOS) 7.1+
* Safari (Mac) 9+"

**Comment by thomasgazzoni** [comment]
That's actually works! 

I guess we could add that fix in the **tick.js**:

```javascript
var originalRequestAnimationFrame = window.requestAnimationFrame || window.webkitRequestAnimationFrame;
```

or change "Chrome" to **Chrome 24+** in the support.md.

**Comment by ewilligers** [comment]
We decided to change the minimum version of Chrome. Due to known security issues, we don't want to encourage users to stick with old versions of Chrome.
