### ISSUE TITLE
Causes IE & Safari to crash

### ISSUE THREAD

**Issue by code-tree** [web-animations/web-animations-js#115]
Including this library causes my app to crash in IE/Edge and Safari (all versions). Works fine in Firefox and Chrome. Crashes during animations, not during load.

I have [reproduced to some degree](http://plnkr.co/edit/jWCTiJxHrCMjLPs5abN6?p=preview), where in IE and Safari the tooltip gets frozen after a while (though doesn't crash browser in this case). Simply hover in and out of button multiple times until tooltip freezes.

**Comment by karlhaas** [comment]
I think we have the same issue. We are using Angular 2 Material and web-animations-js. Error message:
![screenshot from 2017-03-30 07-37-41](https://cloud.githubusercontent.com/assets/7677394/24489134/ebccd206-151b-11e7-9057-ba4f3e928c69.png)

**Comment by karlhaas** [comment]
maybe related to https://github.com/web-animations/web-animations-next/issues/411

**Comment by code-tree** [comment]
Yes, now I check it, it does produce error in the console. My app just crashes so I never got to see any message :stuck_out_tongue:

**Comment by alancutter** [comment]
Release https://github.com/web-animations/web-animations-js/releases/tag/2.2.4 has a fix for this, please let us know whether this is still an issue for you.

**Comment by CodeNameWoods** [comment]
I'm using Safari 11.1 on mac and iOS 11.3 and started getting this issue again:
Unhandled Promise Rejection: TypeError: b[d].push is not a function. (In 'b[d].push(e)', 'b[d].push' is undefined)
