### ISSUE TITLE
[bug report & feature request]Android 4.3 surport

### ISSUE THREAD

**Issue by zhaxi** [web-animations/web-animations-js#136]
Hi, I'm using web-animation-js for a mobile project that need to run  on both ios&android, while below android 4.4 , there's no window.requestAnimationFrame, so in tick.js
```
  var originalRequestAnimationFrame = window.requestAnimationFrame;
  var rafCallbacks = [];
  var rafId = 0;
  window.requestAnimationFrame = function(f) {
    var id = rafId++;
    if (rafCallbacks.length == 0 && !WEB_ANIMATIONS_TESTING) {
      originalRequestAnimationFrame(processRafCallbacks);
    }
    rafCallbacks.push([id, f]);
    return id;
  };
```
originalRequestAnimationFrame will be undefined, hence we will have exception here.

I hope web-animation-js will fix this issue and support android.

**Comment by alancutter** [comment]
We have decided against supporting very old versions of browsers as they often have unpatched security holes. This isn't something we wish to encourage or maintain.

You are free to create your own mini implementation of requestAnimationFrame() using setTimeout() before loading the polyfill if you still wish to support those browsers.
