### ISSUE TITLE
Single keyframes unsupported

### ISSUE THREAD

**Issue by mattkrick** [web-animations/web-animations-js#14]
In the spec, we're given the following example: 
 `elem.animate({ left: '100px' }, 3000);`
As written, this throws the following error:
    `TypeError: Keyframe effect must be null or an array of keyframes.`

So, I make it a single-element array:
    `elem.animate([{ left: '100px' }], 3000);`
And I try to explicitly declare the offset
    `elem.animate([{offset: 0}, { left: '100px', offset: 1}], 3000);`
Both return
    `NotSupportedError: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.`

Not sure if this is a bug or just a document that needs an update, but given these limitations, how can I animate starting from a current position? For example, if I don't know what the element's 'left' property is, but I know I want it to end up at 100px.

**Comment by hgl** [comment]
If this isn't supported, how to unhidden a box before animating it? For example

```js
new AnimationSequence([
    new Animation(elem, {display: "block"}),
    new Animation(elem, [
        {opacity: 0},
        {opacity: 1}
    ], 1000)
]);
```

**Comment by hgl** [comment]
Never mind. Just realized I could use effect callback in a zero duration animation, and manually change the style.

Maybe single keyframe in a zero duration animation could be supported first?

**Comment by morgs32** [comment]
I also would love to have the single keyframe. How else am I to chain a style change (or hide/unhide) after a series of animations.
Can we get this to work? `elem.animate({ opacity: 0 }, { fill: 'forwards' }); ` from http://w3c.github.io/web-animations/#script-execution-and-live-updates-to-the-model

**Comment by shans** [comment]
This is definitely on our roadmap, but it's not trivial due to the need to support additive animations.

We'll get there, but not soon.

**Comment by morgs32** [comment]
Thanks for letting us know, anyway. Keep up the hard work

**Comment by shans** [comment]
Additive animation feature tracking here: https://github.com/web-animations/web-animations-next/issues/325

**Comment by gibbok** [comment]
Currently I am trying to "simulate" additive animations using Web Animations API.
As @dstockwell pointed out I am using `getComputedStyle(element)`.

The problem I am facing is that the matrix3d returned by `getComputedStyle(element).transform` probably does not contain enough information on perspective, so if I am using as start keyframe, animations are not the same (issue with Red box)

In this example, the blue box has the desired animation, red box animation is not correct:

https://jsfiddle.net/gibbok/y3mbqtah/

I would like to know if a solution to this problem exists.
Thanks for your time.

```html
<div id="wrapper">
  <div id="target"></div>
</div>

<div id="wrapper2">
  <div id="target2"></div>
</div>
```
```js
var elem = document.getElementById('target');
var style = window.getComputedStyle(elem);

elem.animate([{
  transform: style.transform // using matrix3d returned from getComputedStyle()
}, {
  transform: 'rotateY(179deg) scaleZ(2) translateZ(200px)'
}], {
  duration: 3000
});

var elem2 = document.getElementById('target2');
elem2.animate([{
  transform: 'rotateY(-179deg) scaleZ(2) translateZ(200px)'
}, {
  transform: 'rotateY(179deg) scaleZ(2) translateZ(200px)'
}], {
  duration: 3000
});
```
```css
#wrapper,
#wrapper2 {
  perspective: 1000px;
}

#target,
#target2 {
  position: absolute;
  top: 100px;
  width: 200px;
  height: 300px;
}

#target {
  left: 100px;
  background-color: red;
  transform: rotateY(-179deg) scaleZ(2) translateZ(200px);
}

#target2 {
  left: 400px;
  background-color: blue;
  transform: rotateY(-179deg) scaleZ(2) translateZ(200px);
}
```
