### ISSUE TITLE
Where is web-animations.min.js file in the repository.

### ISSUE THREAD

**Issue by netdeamon** [web-animations/web-animations-js#143]
I am not able to find the webanimations.min.js file in this repository. But the example in md file shows the use of min file.
```
<!-- Include the polyfill -->
<script src="web-animations.min.js"></script>
```

Also I came from angular [animations documentation](https://angular.io/docs/ts/latest/guide/animations.html), which refers to this repository to grab the min file.

**Comment by saadel** [comment]
There are no minified files in the dev branch, make sure you switch to master, also see #140

**Comment by netdeamon** [comment]
@saadel Thankyou !
