### ISSUE TITLE
EXCEPTION: Animation to or from an underlying value is not yet supported.

### ISSUE THREAD

**Issue by kukjevov** [web-animations/web-animations-js#146]
Angular project is using this polyfill for their animations. 

Here is some interesting issue https://github.com/angular/angular/issues/14752 which is trying to use auto styles computation for `background-color`, but it fails. 

https://plnkr.co/edit/JdctUV6hVfcOhdCbCyMk?p=preview

When you enable native web animations api in firefox using **dom.animations-api.core.enabled** it starts working. 

Is it possible to make this working using this polyfill? Or it is out of scope of javascript implementation?

**Comment by Alucardz** [comment]
Whatever broke it was introduced in 4.2.0-rc.0, proofe is if you set at the top of config.js:
`window.AngularVersionForThisPlunker = '4.1.3'`

your plunker works fine.

**Comment by kukjevov** [comment]
It looks like they have fixed it in version 4.3.1. So looks fine.

Thanks
