### ISSUE TITLE
Chrome bug with GroupEffect and SequenceEffect

### ISSUE THREAD

**Issue by LazyElephant** [web-animations/web-animations-js#147]
This bug manifests in two situations when playing an animation in reverse:
  1. Creating a GroupEffect in which the KeyframeEffects have different durations or delays.
  2. Using a SequenceEffect

When playing the animation forwards, it works.  Playing it in reverse causes desktop Chrome to crash and does some funky animations on android chrome.

This [example](https://codepen.io/LazyElephant/pen/owqZvP) on codepen demonstrates the bug. 

Edit:  I changed the example to a simpler one with just the problem code.

**Comment by Martin-Pitt** [comment]
Curiously wasn't getting a crash in desktop Google Chrome Canary versions 62.0.3164.0 & 62.0.3167.0

On Google Chrome stable 59.0.3071.115 I only managed to reproduce a crash if I played the second box forward once, WAITED +3 seconds, then clicked to go reverse – which immediately crashed the tab.

However, updating my stable Chrome to 60.0.3112.78, I was not able to achieve a crash with the same steps.

**Comment by notoriousb1t** [comment]
I just worked around this issue in Chrome 59 while working on just-animate (a library that uses WAAPI).  I'm not sure of the actual cause, but I also was not able to reproduce it on Chrome 62 or in FireFox either.  I suspect setting currentTime in mass succession on a set of delayed element with a playbackRate of -1 is the trigger.

I was using Chrome's native implementation of element.animate(), so I don't believe this is an issue with the polyfill, but rather a Chrome bug that the polyfill is tripping over.

**Comment by Martin-Pitt** [comment]
This issue is probably going to be irrelevant very quickly now that version 60 is the stable channel, if indeed this was only affecting 59. I've not been able to find any relevant chromium issue that relates to this crash.

**Comment by LazyElephant** [comment]
Yes, it appears chrome 60 has resolved this.
