### ISSUE TITLE
Playing AnimationGroup hits AnimationTiming.playbackRate deprecation message.

### ISSUE THREAD

**Issue by alancutter** [web-animations/web-animations-js#15]
Using `web-animations-next-lite.dev.js` the line `document.timeline.play(new AnimationGroup());` reports the following in the console:

> Web Animations: AnimationTiming.playbackRate is deprecated and will stop working on Sat Feb 28 2015. Use AnimationPlayer.playbackRate instead.

**Comment by dstockwell** [comment]
Can we just silence the message when the playbackRate is set to 1?

**Comment by shans** [comment]
Probably - might need to augment the deprecation function a bit. I'll check
it out.
