### ISSUE TITLE
web-animations.min.js missing in 2.3.0 release

### ISSUE THREAD

**Issue by PhilippSoehnlein** [web-animations/web-animations-js#157]
Neither the ZIP file on the github release page nor the npm package contains `web-animations.min.js`, but it's still referenced in the `package.json`'s `main`-entry.

In my case this breaks my webpack build.

**Comment by janvandenberg** [comment]
I've got the same issue. Well .. everyone using 2.3.0 version is experiencing this issue :-)

**Comment by soniar4i** [comment]
I've got the same error: Module not found: Error: Can't resolve 'web-animations-js and yes, I'm using 2.3.0 version.

**Comment by maartenschelven** [comment]
Same here

**Comment by darrnshn** [comment]
Sorry about that! Should be fixed in https://github.com/web-animations/web-animations-js/releases/tag/2.3.1 now :)

**Comment by alancutter** [comment]
All appears well again with 2.3.1 but for thoroughness can someone who experienced the issue please confirm that it is now resolved?

**Comment by irundaia** [comment]
@alancutter I had the same issue with version `2.3.0`, So, I downloaded the zip from the releases page, and placed the contents in my `node_modules`. That solved the issues for me. 

Would it then be possible to release the new version to npm?

**Comment by lyslim** [comment]
Confirmed, with 2.3.1, it is working fine now..

**Comment by alancutter** [comment]
The NPM package is up to date with the 2.3.1 release.
Thanks for confirming.
