### ISSUE TITLE
Cannot set property _isFinished of #<Object> which has only a getter

### ISSUE THREAD

**Issue by zh99998** [web-animations/web-animations-js#160]
I got `Cannot set property _isFinished of #<Object> which has only a getter`
in https://github.com/web-animations/web-animations-js/blob/master/src/animation.js#L194

seems `_isFinished` is only a getter but `cancel()` trying to set value.

**Comment by ewilligers** [comment]
We'll need more information if we are to reproduce this.
For example, which browser version are you using?

**Comment by dstockwell** [comment]
It might help, but if you look at the code it seems pretty obviously broken.

**Comment by zh99998** [comment]
yes it's obviously broken, not browser related, any browser without native Web Animation API could reproduce it

**Comment by dstockwell** [comment]
@ewilligers this should  repro with `'use strict';` enabled. It's probably safe to remove the line setting `_isFinished`, since it's a no-op otherwise.
