### ISSUE TITLE
Bug: Error Thrown On 'n.style._clear(t.propertyName(e))') On Old Iphone

### ISSUE THREAD

**Issue by david-riyo** [web-animations/web-animations-js#161]
Error: undefined is not a function (evaluating 'n.style._clear(t.propertyName(e))')
web-animations-js: 2.3.1
How to reproduce: open page under iOs7, Safari: Chrome35, error was pop up

suspect error was caused by function ensureStyleIsPatched in apply-preserving-inline-style.js

![image](https://user-images.githubusercontent.com/22925719/28950453-556fc020-7907-11e7-9e23-905cf78d1293.png)

thanks

**Comment by david-riyo** [comment]
pull request: https://github.com/web-animations/web-animations-js/pull/166

**Comment by david-riyo** [comment]
pull request is created to avoid function being called if it is undefined

**Comment by david-riyo** [comment]
same issue happens on linux+ firefox 49, windows 10 + chrome 59.0.3071

**Comment by adamkundrat** [comment]
Hi Guys, do you have any suggestions on how to fix this? This is continuously happens on iPhone 5. We're experiencing same issue. There seems to be pull request are you able to merge and release? Thanks

**Comment by ewilligers** [comment]
See [docs/support.md](https://github.com/web-animations/web-animations-js/blob/dev/docs/support.md)

The polyfill is supported on modern versions of all major browsers, including:
- Safari (iOS) 7.1+
- Safari (Mac) 9+

In particular, the polyfill requires requestAnimationFrame. If your browser does not have requestAnimationFrame, consider loading a requestAnimationFrame polyfill first ([example](https://gist.githubusercontent.com/paulirish/1579671/raw/682e5c880c92b445650c4880a6bf9f3897ec1c5b/rAF.js)).
