### ISSUE TITLE
window.requestAnimationFrame undefined on Android 4.3

### ISSUE THREAD

**Issue by AntiMoron** [web-animations/web-animations-js#162]
OS: android 4.3

```window.requestAnimationFrame == undefined```

Needs to be fixed.

**Comment by AntiMoron** [comment]
Pull request created.

https://github.com/web-animations/web-animations-js/pull/163

Please review the code.
@rjwright

**Comment by ewilligers** [comment]
We have now clarified "modern versions" in [docs/support.md](https://github.com/web-animations/web-animations-js/blob/dev/docs/support.md)

The polyfill is supported on modern versions of all major browsers, including:
- Chrome 55+
- ...

In particular, the polyfill requires requestAnimationFrame. If your browser does not have requestAnimationFrame, consider loading a requestAnimationFrame polyfill first ([example](https://gist.githubusercontent.com/paulirish/1579671/raw/682e5c880c92b445650c4880a6bf9f3897ec1c5b/rAF.js)).

Your [example](https://github.com/web-animations/web-animations-js/pull/163#issuecomment-320617649) works too.
