### ISSUE TITLE
AnimationPlayer is no longer a EventTarget

### ISSUE THREAD

**Issue by hgl** [web-animations/web-animations-js#17]
Currently, web-animations-js implements `AnimationPlayer` as `EventTarget`, but the spec says it should expose `ready` and `finished` promises instead. I wonder if there is any plan to implement these?

I guess the current implementation is of an older spec? Chrome also doesn't expose these two properties, so maybe it should be polyfilled as well.

**Comment by rjwright** [comment]
We plan implement the promises in the polyfill at some point. They will also be implemented natively in Chrome.

**Comment by dstockwell** [comment]
It will be an EventTarget once again, in addition to ready and finished.

See: https://github.com/w3c/web-animations/issues/71

**Comment by rjwright** [comment]
Tracking bug: https://github.com/web-animations/web-animations-next/issues/324
