### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating 'i(d)')

### ISSUE THREAD

**Issue by gatimus** [web-animations/web-animations-js#171]
On Safari 5.1.7, from blank new angular-cli project:

polyfills.ts
```ts
...
/**
 * Required to support Web Animations `@angular/animation`.
 * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
 **/
import 'web-animations-js';  // Run `npm install --save web-animations-js`.
...
```

**Comment by ewilligers** [comment]
See [docs/support.md](https://github.com/web-animations/web-animations-js/blob/dev/docs/support.md)

The polyfill is supported on modern versions of all major browsers, including:
- Safari (iOS) 7.1+
- Safari (Mac) 9+

In particular, the polyfill requires requestAnimationFrame. If your browser does not have requestAnimationFrame, consider loading a requestAnimationFrame polyfill first ([example](https://gist.githubusercontent.com/paulirish/1579671/raw/682e5c880c92b445650c4880a6bf9f3897ec1c5b/rAF.js)).

**Comment by mbenitez01** [comment]
When running ANY .html page in the decompressed file downloaded from github, all I get are blank pages.
Firebug shows all code deployed....no errors...
