### ISSUE TITLE
Who owns the copyright of this repository?

### ISSUE THREAD

**Issue by RicardoBB** [web-animations/web-animations-js#186]
I know this is open source, but even open source code copyright is owned by an organization or people.  The account is "web-animations".  Who owns this project?
I just need this for paperwork.  Not trying to sell or buy anything.

**Comment by alancutter** [comment]
This is the copyright message that gets bundled with web-animations-js: https://github.com/web-animations/web-animations-js/blob/dev/templates/boilerplate
