### ISSUE TITLE
Please provide unminified versions

### ISSUE THREAD

**Issue by hgl** [web-animations/web-animations-js#19]
Sometimes I'd like to debug into web-animations, but mangled local variables make this process pretty hard, even with the source map.

Could you please provide unminified versions of the polyfills, which should be a direct concatenation of source files? That would make debugging a lot easier.

Thanks.

**Comment by rjwright** [comment]
The .dev files are not minified. Note, however, that the .min versions will use native browser animations in Chrome, whereas the .dev versions will not.

**Comment by hgl** [comment]
.dev files doesn't play nice with a module loader like systemjs. The scripts try to inject source files directly, thus using incorrect urls for them (source files no longer live in the same directory as the entry point when managed by a package manager).
