### ISSUE TITLE
Opacity reset to initial value when animation ends

### ISSUE THREAD

**Issue by ofirdev** [web-animations/web-animations-js#23]
When using opacity effect in Chrome, the opacity jumps back to the initial element opacity when the animation ends.

Tested with Chrome 40.0.2214.115 m, Windows 7, web-animations.js 1.0.6

In the following example, the initial opacity of the div is 0.
When clicking on the startAnimation button, the opacity is animated from 0 to 1.
When the animation ends, the opacity jumps back to 0.
I would expect the opacity to stay at 1.
Am I doing something wrong?

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>web animations</title>
    <script>
        var startAnimation = function() {
            var elem = document.querySelector('#elem');
            var player = elem.animate([
                {opacity: getComputedStyle(elem).opacity},
                {opacity: 1.0}
            ], {
                duration: 500
            });
        };
    </script>
</head>
<body>
    <div id="elem" style="width:150px; opacity: 0;">Hello world!</div>
    <button onClick="startAnimation()">Start Animation</button>
    <script type="text/javascript" src="web-animations.min.js"></script>
</body>
</html>
```

**Comment by dstockwell** [comment]
This behavior is correct, you can use `fill: 'forwards'`

        var startAnimation = function() {
            var elem = document.querySelector('#elem');
            var player = elem.animate([
                {opacity: getComputedStyle(elem).opacity},
                {opacity: 1.0}
            ], {
                duration: 500,
                fill: 'forwards',
            });
        };

**Comment by ofirdev** [comment]
Thanks
