### ISSUE TITLE
Failure to animate when 'initial' or 'inherit' is specified.

### ISSUE THREAD

**Issue by sholladay** [web-animations/web-animations-js#24]
**The problem:**
The API exposed by this polyfill exhibits different behavior than Chrome when given some input.

**Current behavior:**
Attempting to animate the background color property from/to certain specific values (at least `initial` and `inherit`), causes it to "blink" / instantly change between those values.

**Expected behavior:**
The animation smoothly moves between the supplied values.

**Seen on:**
* OS X 10.10.1
  * Safari 8.0.2
  * Firefox 35.0.1

**Test case:**
1. Visit [example.com](http://example.com "Example website").
2. Inject [web-animations.min.js](https://raw.githubusercontent.com/web-animations/web-animations-js/master/web-animations.min.js "web animations polyfill") (for example).
3. Run:
````javascript
document.body.animate(
    [
        {
            background: 'initial'
        },
        {
            background: 'red'
        },
        {
            background: 'initial'
        }
    ],
    {
        duration   : 4000,
        iterations : 4
    }
);
````

As proof that the `initial` value triggers the unexpected behavior, the same test case modified only slightly exhibits the expected behavior:
```javascript
document.body.animate(
    [
        {
            background: 'blue'
        },
        {
            background: 'red'
        },
        {
            background: 'blue'
        }
    ],
    {
        duration   : 4000,
        iterations : 4
    }
);
````

**Comment by shans** [comment]
We'll probably never support inherit in the polyfill, as it's really hard to do.

Initial should work, though.

**Comment by sholladay** [comment]
Fair enough. That's convenient for me, since initial is what I really wanted when I discovered this. I just tried inherit to see what would happen, while trying to find a workaround.

**Comment by shans** [comment]
Tracking issue: https://github.com/web-animations/web-animations-next/issues/327
