### ISSUE TITLE
Animate clip-path

### ISSUE THREAD

**Issue by ofirdev** [web-animations/web-animations-js#25]
Is animating clip-path supported?
In the following example elem.animate() on clip-path has no effect.
Tested with Chrome 41.0.2272.76 m, Windows 7, web-animations.js 1.0.6
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>web animations</title>
    <script>
        var startAnimation = function() {
            var elem = document.querySelector('#elem');
            var player = elem.animate([
                {"clip-path": "polygon(0% 0%, 100% 0%, 100% 0%, 0% 0%)"},
                {"clip-path": "polygon(0% 0%, 100% 0%, 100% 100%, 0% 100%)"}
            ], {
                duration: 1000,
				fill: 'forwards'
            });
        };
    </script>
</head>
<body>
    <div id="elem" style="width:150px;">Hello world!</div>
    <button onClick="startAnimation()">Start Animation</button>
    <script type="text/javascript" src="web-animations.min.js"></script>
</body>
</html>
```

**Comment by rjwright** [comment]
Hey ofirdev,

Animating clip-path is not supported at the moment. Does clip-path work for you in chrome as a simple style declaration (not in an animation)? It seems like you have to pass the shape as a uri to make it work.

**Comment by ofirdev** [comment]
@rjwright yes, clip-path works on Chrome 41 with -webkit- prefix.
You can click on the shapes on the right to see the image clipped in this example (doesn't work in Firefox and IE):
http://bennettfeely.com/clippy/

I also tried using a shape as a uri but couldn't animate the SVG clipPath element's hight.
```html
<defs>
  <clipPath id="path">
      <rect height="0" width="100" x="100" y="100">
      </rect>
  </clipPath>
</defs>
```

```javascript
new Animation(rectEl,
      [{"height": "0"}, {"height": 100}],
       {duration: 5000, iterations: 1, fill: 'forwards'});
```

**Comment by dstockwell** [comment]
We'll implement this at some point. It's a little tricky as Blink/WebKit have a SVG clip-path property which is distinct from -webkit-clip-path.

**Comment by shans** [comment]
Tracking issue: https://github.com/web-animations/web-animations-next/issues/326
