### ISSUE TITLE
Reflect updated Web Animations API?

### ISSUE THREAD

**Issue by davidkpiano** [web-animations/web-animations-js#28]
The spec for the Web Animations API has been updated on March 13th, 2015: https://w3c.github.io/web-animations/ - items include simplification and the moving of `AnimationGroup` and `AnimationSequence` (now `GroupEffect` and `SequenceEffect`) to Level 2.

Will you guys reflect on these API changes or still be based on the old version of the spec?

**Comment by dstockwell** [comment]
We'll be making the changes in the near future. There will be a deprecation period where both sets of names work.

**Comment by samthor** [comment]
This is resolved as of the [2.0.0 release](https://github.com/web-animations/web-animations-js/tree/2.0.0).
