### ISSUE TITLE
Minified import

### ISSUE THREAD

**Issue by nevir** [web-animations/web-animations-js#29]
Currently, we're using [core-animation/web-animations.html](https://github.com/Polymer/core-animation/blob/master/web-animations.html) as our shared import for WA in Polymer. I think it's more desirable for us to just depend on web-animations-js directly

I'm not clear on how the imports should be structured, though:
- `web-animations.min.html`/`web-animations-next.min.html`/`web-animations-next-lite.min.html`?
- Convert the existing imports over to `.dev.html`? (this would match existing patterns better)

Also, I worry about some components wanting to import lite, and others wanting the full library

cc @morethanreal

**Comment by dstockwell** [comment]
I think adding `*.min.html` files which just load the matching scripts would be fine.

I'm not yet sure how we can support pages trying to load multiple versions of the polyfill.

**Comment by shans** [comment]
Will multiple loaded versions be an issue? If so we should figure out some way to suppress duplicate includes.

**Comment by bedeoverend** [comment]
Any chance this'll be added soon? `*.min.html` would be perfect

**Comment by suzyh** [comment]
I believe this has now been fixed.
