### ISSUE TITLE
Play a SequenceEffect infinitely 

### ISSUE THREAD

**Issue by interactionist** [web-animations/web-animations-js#31]
Hi.

Is it possible now to play a ```SequenceEffect``` infinitely, like specifying ```iterations: infinite```?

Thanks.

**Comment by interactionist** [comment]
I see the timing applied to the SequenceEffect, but it only plays once (instead of the specified iterations counts)

```Javascript
window.SequenceEffect
    _timing: Object
    activeDuration: (...)
    animation: b.Animation
    children: Array[3]
    timing: Object
        delay: 0
        direction: "normal"
        duration: "auto"
        easing: "linear"
        endDelay: 0
        fill: "both"
        iterationStart: 0
        iterations: 3
        playbackRate: 1
```

**Comment by shans** [comment]
Iterations aren't supported on groups yet. Feature request tracked here: https://github.com/web-animations/web-animations-next/issues/322
