### ISSUE TITLE
`Animation.finished` seems not be polyfilled

### ISSUE THREAD

**Issue by vanthome** [web-animations/web-animations-js#33]
Hi,
I've written a mixin for event based animation control.
It works in latest Chrome but fails in FF 38 on this line
as `currAnim.finished` is undefined:
https://github.com/ember-vcl/evented-animation-support/blob/master/main.js#L86
As far as I understand the docs this should be polyfilled or am I wrong?

**Comment by vanthome** [comment]
Update, it also fails in Opera 30.

**Comment by rjwright** [comment]
Hi vanthome,

I'm not sure why this isn't working. The finished animation promise has been polyfilled since [version 2.1.0](https://github.com/web-animations/web-animations-js/releases/tag/2.1.0).

Do you have a demo of it failing? JS Bin or similar would be ideal.

**Comment by dstockwell** [comment]
Closing since there is no further information.

**Comment by duivvv** [comment]
having the same issue here, polyfill for animation works but when I add a console.log it indicates that finished.then is undefined

```js

  animation = $rect.animate({
    opacity: [0.5, 1],
    backgroundColor: [`#ffc`, `#ccf`],
    left: [`0rem`, `20rem`]
  }, {
    direction: `alternate`,
    duration: 500,
    iterations: 3,
  });

  console.log(animation.finished.then);

```
> undefined is not an object (evaluating 'animation.finished.then')

**Comment by vanthome** [comment]
Thx for proving me finally :)

**Comment by simevidas** [comment]
@AdaRoseEdwards has written a polyfill: https://gist.github.com/simevidas/2e721c8e6d67f04b5e1a0083c542a767

**Comment by TechQuery** [comment]
I find that only `next` version has `finished` promise polyfill...
https://cdn.jsdelivr.net/npm/web-animations-js@2.3.2/web-animations-next.min.js
