### ISSUE TITLE
window.performance not available on mobile safari

### ISSUE THREAD

**Issue by sfeast** [web-animations/web-animations-js#35]
This line - https://github.com/web-animations/web-animations-js/blob/master/src/tick.js#L80 - errors on mobile safari (< version 9) since window.performance isn't supported there - http://caniuse.com/#search=performance

**Comment by shans** [comment]
Fix looks good, thanks. Would you mind sending a PR against the web-animations-next repository at http://github.com/web-animations/web-animations-next (this one is just for releases)?

**Comment by samthor** [comment]
This is fixed in #403.
