### ISSUE TITLE
Animate scrollLeft and scrollTop

### ISSUE THREAD

**Issue by M0nter0** [web-animations/web-animations-js#38]
I would like to animate a movement in the scrollbar.

If I use 

`.animate( { scrollLeft: '500' }, 1000 );`

I just get the Single keyframes unsupported error commented at #14  

So I changed it to : 

`.animate([{scrollLeft:0},{scrollLeft:500}], 3000);`

But nothing happens. I suppose is because it's expecting a css property, but `scrollLeft` is not. If I use something like

`.animate([{Left:0},{Left:3000}], 3000);`

It works properly.

Any idea of how to accomplish this?

**Comment by Yaffle** [comment]
@M0nter0 
You could try with "smooth scroll API" - https://code.google.com/p/chromium/issues/detail?id=243871

**Comment by dstockwell** [comment]
This isn't in scope of the polyfill, you can submit your suggestion against the specification at https://github.com/w3c/web-animations or via email to https://lists.w3.org/Archives/Public/public-fx/
