### ISSUE TITLE
Cannot read property 'cancel' of null

### ISSUE THREAD

**Issue by recanti** [web-animations/web-animations-js#39]
I'm trying to use the polyfill on Codepen and I keep running into this error. The full message is as follows:

`Uncaught TypeError: Cannot read property 'cancel' of null`
`b.Animation @ pen.js:1772`
`window.onload @ pen.js:2134`

This happens when using both the 2.1.2 version of the minified file, as well as the 2.1.1 version. A link to the pen can be found [here](http://codepen.io/recanti/pen/YyKowW/)

**Comment by shans** [comment]
```
  var anim = new Animation(
    blah, [{
      opacity: 0
    }, {
      opacity: 1
    }],
    1000);
```
This code is incorrect - Animation doesn't take these parameters, KeyframeEffect does. (The specification renamed some terms recently which led to this confusion.)

You probably just want to use Element.animate, btw:
```
anim = blah.animate([{opacity: 0}, {opacity: 1}], 1000);
```

**Comment by recanti** [comment]
Thanks shans. I was trying to follow the format that was used on the [Polymer project page](https://www.polymer-project.org/0.5/platform/web-animations.html). This is a top search result and I get linked to it often. Is this incorrect, or has the spec changed since then?

**Comment by shans** [comment]
Yup, the spec changed. Looks like the Polymer documentation's updated now too, due to your bug. Thanks for following this up so diligently!

**Comment by recanti** [comment]
No problem! The Web Animations spec seems really interesting and I'm just glad to have accurate documentation for it.
