### ISSUE TITLE
what is the actual browser support for _this_ library?

### ISSUE THREAD

**Issue by NickStefan** [web-animations/web-animations-js#43]
Browser support is pretty obfuscated. I go to this page: https://www.polymer-project.org/0.5/resources/compatibility.html

That page shows chrome as being the only supported browser for web animations. But i read further down to the polyfill browser support section which then directs me to a web components polyfill or a compatability matrix: https://github.com/WebComponents/webcomponentsjs#browser-support

That matrix only mentions: Custom Elements, HTML Imports, Shadow DOM and Templates.
No mention of the web animation API. And now I'm confused, do I need a webcomponents polyfill to use the web-animations polyfill?

So where can I find the actual browser support of _this_ library as a standalone?

**Comment by NickStefan** [comment]
I still can't find a definitive answer, but would these SauceLabs tests in the repo indicate that the library is targeting to polyfill non-native for only these browsers?

ie11, firefox 27+, safari 7.1+ ?

```
    sl_chrome: {
      base: 'SauceLabs',
      browserName: 'chrome',
      platform: 'Windows 7'
    },
    sl_firefox: {
      base: 'SauceLabs',
      browserName: 'firefox',
      version: '27'
    },
    sl_ios_safari: {
      base: 'SauceLabs',
      browserName: 'iphone',
      platform: 'OS X 10.9',
      version: '7.1'
    },
    sl_ie_11: {
      base: 'SauceLabs',
      browserName: 'internet explorer',
      platform: 'Windows 8.1',
      version: '11'
    }
```

**Comment by shans** [comment]
Web Animations is actually listed on the linked page? You might need to scroll..

Nevertheless, that refers to native support only. The sauceLabs list you found is correct (i.e. latest Firefox, Safari, IE are supported), with the caveat that there are some minor differences in getComputedStyle outputs which mean some tests will not pass despite the library behaving correctly.

@samthor could you update the README with this info? Also the Polymer pages should refer to polyfill support not native support.

**Comment by kevin-smets** [comment]
So no IE10 or IE9? What about mobile browsers? Imo it should look a bit like a search on caniuse.

**Comment by samthor** [comment]
So this is tracked on the [Polymer docs](https://github.com/Polymer/docs/issues/1360): they know it's confusing. As @shans suggests I'll just update our `README.md` to include support levels directly.
