### ISSUE TITLE
Kindly remove compressed archive web-animations.min.js.gz from bower

### ISSUE THREAD

**Issue by kishaningithub** [web-animations/web-animations-js#44]
Hi,
 The existence of compressed archive  "web-animations.min.js.gz" is making
phone gap build fail with the below error.

Error - A compressed file is in your app and a step in the android tool chain doesn't allow multi-level compression. Please remove this file from your application: dist/bower_components/web-animations-js/web-animations.min.js.gz

**Comment by kishaningithub** [comment]
Hi,
  i could see the gz file in my local repository even after doing a bower update. The following is my bower.json file


{
  "name": "polymer-starter-kit",
  "private": true,
  "dependencies": {
    "polymer": "Polymer/polymer#^1.1.0",
    "iron-elements": "PolymerElements/iron-elements#^1.0.0",
    "paper-elements": "PolymerElements/paper-elements#^1.0.1",
    "platinum-elements": "PolymerElements/platinum-elements#^1.1.0",
    "neon-elements": "PolymerElements/neon-elements#^1.0.0",
    "page": "visionmedia/page.js#~1.6.3",
    "firebase-element": "GoogleWebComponents/firebase-element#~1.0.6"
  },
  "devDependencies": {
    "web-component-tester": "*",
    "test-fixture": "PolymerElements/test-fixture#^1.0.0"
  }
}

**Comment by dstockwell** [comment]
We will need to tag a new release.

**Comment by dstockwell** [comment]
Published https://github.com/web-animations/web-animations-js/releases/tag/2.1.3
