### ISSUE TITLE
Web-animations.min.js throw exception when using it with Webpack

### ISSUE THREAD

**Issue by AmberDeBlack** [web-animations/web-animations-js#45]
Error message:
Cannot set property 'true' of undefined

Error occurred on the very first line:
function(a,b){b["true"]=a

Reason - window object is captured with incorrect code:
function(){return this}

Correct way to get window object (this code taken from jQuery source):
typeof window !== "undefined" ? window : this

**Comment by dstockwell** [comment]
What is Webpack? The capturing of window seems to be a result of uglify.

**Comment by shans** [comment]
(i.e. this is not a bug in web-animations - would you mind following up with the authors of uglify?)

**Comment by AmberDeBlack** [comment]
Okay, I have examined your Gruntfile.js

In function compress(...) at line #59 you enable option of UglifyJS:
record.options.wrap = true;

What actually this option do?...

It considers that your code is CommonJS module
and wrap it with function 
for using it in browser:

	(function(exports,global){
		global[""]=exports;
		/* 
			Your module code

			exports.blablabla = function() { ... };
		*/
	)({},function(){return this}());


Since your code is web-browser polyfill (not a CommonJS module) 
and it doesn't export anything with "exports" variable
then you have no need of using "wrap = true" option.

Also this will fix compatibility problem with Webpack and Browserify.

**Comment by xseignard** [comment]
Hello,
It seems this problem is still happening, isn't it?

Any hints an fixing this?

Best regards,

Xavier

**Comment by AmberDeBlack** [comment]
@xseignard 

Try replace this (in the end of web-animations.min.js file):

    function(){return this}()

With this:

    typeof window !== "undefined" ? window : this

**Comment by xseignard** [comment]
Hi @AmberDeBlack 
Thanks for the tip! But I will not maintain my own version of the polyfill, the best would be for this polyfill to handle that case since it's a pretty standard case, isn't it?

Best regards,

Xavier

**Comment by AmberDeBlack** [comment]
@xseignard 

Sure :)

But I'm not maintainer of this repo

And maintainer declined my workaround for this problem (read messages above)

**Comment by errorx666** [comment]
I had a similar issue, but apparently it was caused by the `module` option being set on `babel-loader`.  When I set this option to `false` it worked.

**Comment by saadel** [comment]
I still get the same error when I try loading the polyfill with browserify,
even @ujeenator workaround is not working.
any ideas?

**Comment by Brian-McBride** [comment]
I was able to fix this by doing two things:

1. Don't process it by babel-loader. The file is already es5 and minified. No reason to further run it through babel. 
2. Add a shim.
```
{
    test: /web-animations-next-lite.min.js/,
    use: 'imports-loader?this=>window',
},
```
You can tweak this, but basically it is setting the "this" reference to "window".

**Comment by alan-agius4** [comment]
Hi, I really don't agree that this is a not a bug in `web-animation-js`. 

As this issue is also present when not using any bundler nor minifier. If one loads this script using `type="module", it will fail because the `this` context will be `undefined` when adding the `type=module` attribute on a script tag.

```js
<script>
  alert(this);  // = window
</script>

<script type="module">
  alert(this); // = undefined
</script>
```

I hope, that you can reconsider the fact that this is an issue.

Thanks,
