### ISSUE TITLE
Publish 2.1.4 to npm

### ISSUE THREAD

**Issue by marionebl** [web-animations/web-animations-js#50]
Follow-up to: https://github.com/web-animations/web-animations-next/pull/403

2.1.4 contains some new bug fixes and is available on master, which is awesome!
2.1.4 is not published to npm, which makes installing it a bit more laborious than it has to be - please publish to npm.

**Comment by samthor** [comment]
Done.

**Comment by marionebl** [comment]
Awesome! :+1:
