### ISSUE TITLE
Animation cancel event is not polyfilled

### ISSUE THREAD

**Issue by mgiuffrida** [web-animations/web-animations-js#57]
Repro: https://jsfiddle.net/mgiuffrida/cxwoy09f/

The cancel event is not implemented in Chrome (or Firefox?) and isn't firing when using web-animations or  web-animations-next.

Spec: http://w3c.github.io/web-animations/#cancel-event

**Comment by mgiuffrida** [comment]
The `finish` event fires when an animation is canceled in Firefox.

**Comment by birtles** [comment]
Got a test case for that? The cancel event should fire in Firefox if you're using the native implementation of Web Animations. Perhaps you're referring to the polyfill?

**Comment by mgiuffrida** [comment]
@birtles Yes, when using the polyfill in Firefox the `finish` event fires when the animation is cancelled.

Without the polyfill, the fiddle doesn't work:

    TypeError: document.querySelector(...).animate is not a function

I've tried in Firefox 44 with `dom.animations-api.core.enabled` and in Firefox Dev (46.0a2).

**Comment by birtles** [comment]
Right, animate() is only available in Firefox 47.

**Comment by mgiuffrida** [comment]
You're right, I didn't notice that. But it's still a bug in the polyfill, yes? It shouldn't fire `finish` on `cancel()` in FF, irrespective of the `cancel` event not being implemented in the polyfill yet.

**Comment by birtles** [comment]
Yes, that's right. I was just trying to clarify if this was a bug in Firefox or the polyfill. It seems like it's an issue with the polyfill.

**Comment by dstockwell** [comment]
Fixed by https://github.com/web-animations/web-animations-next/pull/416
