### ISSUE TITLE
'fill: "forwards"' causes the element to ignore any future style changes.

### ISSUE THREAD

**Issue by urandom** [web-animations/web-animations-js#59]
Hi,

Using fill: forwards when starting an animation somehow disables all style changes after the animation ends. This can very easily be tested by doing:

`$('body').animate([{opacity: 1}, {opacity: 0.3}], {duration: 400, fill: 'forwards'})`

and after than ends, running: 

`$('body').style.opacity = 1`

It seems that only the properties that have at some point been part of a forwards animation are 'disabled'.  And this occurs in chrome 48 but not firefox 44

**Comment by dstockwell** [comment]
Working as intended. Discussed further in https://code.google.com/p/chromium/issues/detail?id=585463
