### ISSUE TITLE
Undefined check for _animation in web-animations-next-animation.js

### ISSUE THREAD

**Issue by rishabhtulsian** [web-animations/web-animations-js#65]
Add an undefined check before calling `this._animation.cancel()` at https://github.com/web-animations/web-animations-js/blob/2.0.0/src/web-animations-next-animation.js#L28

Not having the check is causing errors in paper-datatable-card, paper-dropdown, iron-dropdown.

**Comment by tdesc** [comment]
Hello, got same error with polymer and web-animations-next-lite.min.js
Is there fixed version somewhere?
