### ISSUE TITLE
FF nightly throws error: Animation with a target not bound to a document is not yet supported

### ISSUE THREAD

**Issue by ebidel** [web-animations/web-animations-js#66]
`NotSupportedError: Animation with a target not bound to a document is not yet supported.`

It looks like FF nightly has enabled initial support for the Web Animations API?

<img width="1011" alt="b2b339a4-d63a-11e5-9689-fd4c3dec9495" src="https://cloud.githubusercontent.com/assets/238208/13755444/7def1ee8-e9d8-11e5-9247-1dc6dbf6e0c0.png">

Everything works as expected if we turn off `dom.animations-api.core.enabled`.

**Comment by alancutter** [comment]
Correct, Firefox Nightly has an incomplete experimental implementation of Web Animations.

I don't think the polyfill should be attempting to patch over this version of Firefox. Given that there's a separate Firefox Developer Edition I think Nightly is for Firefox developers more so than web developers. 

@birtles: Can you verify that the Developer Edition won't contain the pre-shipped Web Animations implementation?

**Comment by birtles** [comment]
Yeah, Developer Edition currently contains that limitation but it won't ship to beta. I was thinking of turning this off in Developer Edition but have yet to land the patches to do so.

**Comment by ebidel** [comment]
I think one problem we were worried about is that `dom.animations-api.core.enabled` is on by default in FF nightly. So we were assuming that this would eventually trickle down to a stable release of FF. Is that not the case?

**Comment by birtles** [comment]
No, that's not the case. It will automatically be turned off when it reaches beta.

**Comment by ebidel** [comment]
Good to know!
