### ISSUE TITLE
Is there more documentation in detail?

### ISSUE THREAD

**Issue by superlin** [web-animations/web-animations-js#69]
It's really a fantastic library, Is there more documentation in detail?

**Comment by rachelnabors** [comment]
It's in progress! I'm writing the docs at MDN right now:
https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API
https://developer.mozilla.org/en-US/docs/Web/API/Animation
https://developer.mozilla.org/en-US/docs/Web/API/KeyframeEffect
https://developer.mozilla.org/en-US/docs/Web/API/Element/animate
