### ISSUE TITLE
Polyfill groups are not guarded on missing a native implementation

### ISSUE THREAD

**Issue by alancutter** [web-animations/web-animations-js#71]
If browsers start natively supporting GroupEffect or SequenceEffect the polyfill will overwrite them with it's own incomplete implementation (group easing is not supported). See src/group-constructors.js.

**Comment by dstockwell** [comment]
This is intentional -- there are no native implementations to fall back on. We don't know what the native implementations of these features are going to look like yet, automatically falling back would likely break content.
