### ISSUE TITLE
minified versions and source-maps

### ISSUE THREAD

**Issue by KnisterPeter** [web-animations/web-animations-js#78]
Since the source-maps does not contain the sources and the npm packages of web-animations-js are distributed without sources the source-maps are useless.

Any tool (e.g. sorcery) trying to resolve source mapping fails, because the references to the source-files in the source-map are not available.

Please add either the source to the source-maps or distribute npm packages with sources (I would prefer the first one).

**Comment by KnisterPeter** [comment]
Thanks

**Comment by alancutter** [comment]
Thanks for reporting the issue.

**Comment by alancutter** [comment]
FYI the fix is now live: https://npmcdn.com/web-animations-js@2.2.2/
