### ISSUE TITLE
incomplete npm package published

### ISSUE THREAD

**Issue by dszmaj** [web-animations/web-animations-js#79]
There are only minified versions of files in the npm, see 
https://npmcdn.com/web-animations-js@2.2.1/

This package is making issues when importing to webpack bundle. Please upload complete repo to to the npm so bundles can be properely optimized :)

**Comment by dszmaj** [comment]
cloning this repo to web-animations-js folder in node_modules solves the problem, proving above

**Comment by alancutter** [comment]
Thanks for reporting the issue.

**Comment by alancutter** [comment]
FYI the fix is now live: https://npmcdn.com/web-animations-js@2.2.2/
