### ISSUE TITLE
Specifying animation easing as a function is deprecated 

### ISSUE THREAD

**Issue by anakinksky** [web-animations/web-animations-js#82]
Getting following warning in Chrome console

> Specifying animation easing as a function is deprecated and all support will be removed in M54, around October 2016, at which point this will throw a TypeError. This warning may have been triggered by the Web Animations or Polymer polyfills. See http://crbug.com/601672 for details.

**Comment by alancutter** [comment]
Which version of the polyfill are you using? I recommend updating to the latest version to see if it fixes the issue.

**Comment by suzyh** [comment]
Closing this issue as we don't have enough info to act on this.
