### ISSUE TITLE
Dashoffset not properly animating in ios 8.1

### ISSUE THREAD

**Issue by filaraujo** [web-animations/web-animations-js#84]
For some reason when animating a svg  dashoffset the animation will stutters.  Settings the values through css works fine, but not when using the animate api.

``` html
<svg width="200" height="200" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
    <circle cx="50" cy="50" r="40" stroke="white" fill="none" stroke-width="10" stroke-linecap="round"/>
    <circle id="line" cx="50" cy="50" r="40" stroke="#808080" fill="none" stroke-width="6" stroke-linecap="round"/>
  </svg>

  <script>
    var line = document.getElementById("line");

    line.animate(
      [
        {strokeDashoffset:0},
        {strokeDashoffset:502}
      ],
      { duration: 2000, iterations: Infinity }
    );
    line.animate(
      [
        {strokeDasharray:"150.6 100.4"},
        {strokeDasharray:"1 250"},
        {strokeDasharray:"150.6 100.4"}
      ],
      { duration: 2000, iterations: Infinity }
    );
  </script>
```

or jsbin
http://jsbin.com/wecabo/1/edit?html,output

**Comment by jakearchibald** [comment]
Your demo doesn't work as you're using `href` rather than `src` on the script element.

But yeah, there seems to be a bug here. The polyfill is only setting `strokeDasharray` to be the first & final values - no interpolation.

**Comment by jakearchibald** [comment]
Seems this property is missing a property handler. It should use the same one as "left" I think.

http://jsbin.com/paxokuyifi/1/edit?html,output - hacked this together. Seems to work.

**Comment by filaraujo** [comment]
@jakearchibald Im assuming in not missing anything - is this what your fix was? #85

**Comment by jakearchibald** [comment]
Looks right to me

**Comment by chiefcll** [comment]
Can we get a release with this code in it?
