### ISSUE TITLE
web-animations-next-lite flicker

### ISSUE THREAD

**Issue by e111077** [web-animations/web-animations-js#86]
On specific versions of chrome stable (53.0.2785.x) we have noticed that some `KeyframeEffect` `translateX` transforms seem to be causing flickers at the end of each animation when something within the animating node is focused (PolymerElements/neon-animation#205).

example:
![image](https://thumbs.gfycat.com/GoodNeatBlobfish-size_restricted.gif)

Interactive:
https://output.jsbin.com/denafe/1

We have been using `web-animations-next-lite.min.js` as the polyfill, but this is not reproducible using `web-animations-next-lite.dev.js`. I tried concatenating the files in the dev build and even minifying it, but was unable to reproduce it. I believe that there may be something gone awry in the build step.

This does not seem to be reproducible in Canary.

**Comment by dstockwell** [comment]
Based on the above, using dev or concatenating the files is probably forcing the polyfill to be used rather than falling back to the native implementation. We should probably refile this as a chromium bug and get a bisect, @alancutter.

**Comment by shawncplus** [comment]
@e111077 @dstockwell Can confirm, replaced direct usage of `web-animations-next-lite.min.js` with an include of `web-animations-next-live-dev.html` and all was well. This is a pretty kludgy workaround seeing as it would require me to localmod two different bower dependencies. So hopefully it gets resolved somewhat soon

**Comment by alancutter** [comment]
This is definitely a Chrome bug rather than the polyfill.
Continuing investigation in: https://bugs.chromium.org/p/chromium/issues/detail?id=649195

**Comment by alancutter** [comment]
BTW a workaround that doesn't involve using the dev polyfill would be to set `Element.prototype.animate = null` before you load the polyfill. This might save you having to mess with bower configs and restrict the workaround to the affected page.
