### ISSUE TITLE
What's the issue with Safari (Mac) 6, 7 & 8?

### ISSUE THREAD

**Issue by code-tree** [web-animations/web-animations-js#91]
Browser support for this polyfill is currently listed as [9+ for Safari Mac](https://github.com/web-animations/web-animations-js/blob/master/docs/support.md#browser-support)

My app currently supports Safari Mac 6+, so I'm a little hesitant to raise that to 9+ (as this polyfill seems to require).

I was just wondering what the issue is with 6/7/8? If I use this polyfill and my app simply won't animate, then that will be fine. But if it breaks my app, then that may be a problem for me.

(Specifically, I hope to use it to animate my Angular 2 routes)

**Comment by maxisam** [comment]
I have the same question too. I want to know what browser function is lacking on them, so I can detect it and disable animation

**Comment by ewilligers** [comment]
Note that we don't test with old browser versions, and we encourage movement to modern browser versions for the security benefits.

A known issue with early Safari versions is that they have webkitRequestAnimationFrame and not requestAnimationFrame.

If you change
    var originalRequestAnimationFrame = window.requestAnimationFrame;
to
    var originalRequestAnimationFrame = window.requestAnimationFrame ||
            window.webkitRequestAnimationFrame;
then the polyfill is likely to work with early Safari versions.

We haven't merged this change as we encourage movement to modern browser versions for the security benefits.

**Comment by code-tree** [comment]
@ewilligers Obviously as a developer I'm all for latest versions! It's our user bases that are the trouble, and having a broken site reflects on the business rather than on the user's need to upgrade. For such a small addition, any chance you can reconsider?

Thanks for the info though
